public with sharing class ConstUtil {
    public static DiscountConst DISCOUNT {
        get {
            return new DiscountConst();
        }
    }

    public static OrderConst ORDER {
        get {
            return new OrderConst();
        }
    }

    public static ConnectedAppsConst CONNECTED_APPS {
        get {
            return new ConnectedAppsConst();
        }
    }

    public static EndpointConst ENDPOINT {
        get {
            return new EndpointConst();
        }
    }

}