name: Validate PR from Feature Branch

on:
  pull_request:
    branches:
      - develop

jobs:
  validate-salesforce-code:
    # Uruchom ten job tylko, jeśli gałąź źródłowa PR zaczyna się od "feature/"
    if: startsWith(github.head_ref, 'feature/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: npm install sfdx-cli --global

      - name: Authenticate to Salesforce Org
        run: |
          sfdx force:auth:password \
            --username ${{ secrets.SALESFORCE_USERNAME }} \
            --password ${{ secrets.SALESFORCE_PASSWORD_WITH_TOKEN }} \
            --clientid ${{ secrets.SALESFORCE_CONSUMER_KEY }} \
            --clientsecret ${{ secrets.SALESFORCE_CONSUMER_SECRET }} \
            --instanceurl ${{ secrets.SALESFORCE_SERVER_URL }} \
            --setalias sfdx-ci-alias
      - name: Validate code against Sandbox
        run: |
          sfdx force:source:deploy \
            --checkonly \
            --sourcepath force-app \
            --targetusername sfdx-ci-alias \
            --testlevel RunLocalTests
