name: Validate PR from Feature Branch

on:
  pull_request:
    branches:
      - develop

jobs:
  validate-salesforce-code:
    if: startsWith(github.head_ref, 'feature/')
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v3

      - name: 'Install Salesforce CLI'
        run: |
          npm install sfdx-cli --global

      - name: 'Authenticate to Salesforce Org'
        run: |
          echo "${{ secrets.SF_SECRET_KEY }}" > server.key
          sfdx auth:jwt:grant \
            --client-id ${{ secrets.SF_CONSUMER_KEY }} \
            --jwt-key-file server.key \
            --username ${{ secrets.SF_USERNAME }} \
            --instance-url ${{ secrets.SF_SERVER_URL }} \
            --set-default-dev-hub \
            --alias FeatureOrg

      - name: 'Deploy to Salesforce Org'
        run: |
          sfdx force:source:deploy -p force-app --testlevel RunLocalTests -u FeatureOrg --checkonly